import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from PyPDF2 import PdfFileWriter, PdfFileReader
import pandas as pd

# EMAIL = "Wdenny007@gmail.com"
# PASSWORD = "MK1*55(0(EV#"


RECEIVER = "f20190478@hyderabad.bits-pilani.ac.in"
NAME = "Aditya Goyal"



# ---------------------------- DICT -> CSV ------------------------------- #

# d = {
#     "name": ["Aditya Goyal", "Anwesan De", "Nirav Jayesh Parmar", "Abhinav Gupta"],
#     "email": ["f20190478@hyderabad.bits-pilani.ac.in", "f20190518@hyderabad.bits-pilani.ac.in",
#               "f20190540@hyderabad.bits-pilani.ac.in", "f20190380@hyderabad.bits-pilani.ac.in"],
#     "dob": ["12042001", "19092000", "07022002", "16012000"]
# }
#
# data = pd.DataFrame(d)
# data.to_csv("Skwad.csv")
# print(data)


# ---------------------------- SETS SENDERS MAIL AND PASS ------------------------------- #

def set_credentials(e, p):
    global email, passw
    email = e
    passw = p


# ---------------------------- ENCRYPTING PDF ------------------------------- #

def encrypt_pdf(file, password):
    out = PdfFileWriter()

    num = file.numPages

    for id in range(num):
        page = file.getPage(id)
        out.addPage(page)

    out.encrypt(password)

    with open("encrypted_file.pdf", "wb") as f:
        out.write(f)


# ---------------------------- SENDING MAILS WITH PDF ------------------------------- #

def send_mail(name, reciever):
    BODY = f'''
    Dear Mr.{name},
    This the test mail by Aditya Goyal.
    Please open it and confirm that it works well.
    THIS IS AN AUTOGENERATED EMAIL.
    DO NOT REPLY.
    G.G.
    '''


    # Setup the MIME
    message = MIMEMultipart()
    message['From'] = email
    message['Bcc'] = reciever
    message['Subject'] = "MASS MAILING TESTING"
    message.attach(MIMEText(BODY, 'plain'))

    pdfname = "encrypted_file.pdf"

    # open the file in binary
    binary_pdf = open(pdfname, 'rb')

    payload = MIMEBase('application', 'octate-stream', Name=pdfname)

    payload.set_payload(binary_pdf.read())


    # encoding the binary into base64
    encoders.encode_base64(payload)


    # add header with pdf name
    payload.add_header('Content-Decomposition', 'attachment', filename=pdfname)
    message.attach(payload)

    with smtplib.SMTP("smtp.gmail.com", 587, timeout=120) as connection:
        connection.starttls()
        connection.login(user=email, password=passw)
        text = message.as_string()
        connection.sendmail(
            from_addr=email,
            to_addrs=reciever,
            msg=text
        )

        print(f"Mail Sent to {name}, email = {reciever}")


# ---------------------------- MAIN FUNCTION ------------------------------- #

def mail_sending(csv_path, file_path):
    file = PdfFileReader(file_path)

    data = pd.read_csv(csv_path)

    for i in range(len(data)):
        encrypt_pdf(file, str(data["dob"][i]))
        send_mail(data["name"][i], data["email"][i])
